# -*- coding: utf-8 -*-
"""Prodigy-InfoTech-DS-Task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18l-XSYINUWNdvnZGqVCmItawyS-LgHAf
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.datasets import fetch_20newsgroups
from nltk.corpus import stopwords
import string
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

import nltk
nltk.download('stopwords')

import pandas as pd

# Try specifying the separator and handling errors
data = pd.read_csv('/content/twitter_training.csv', sep=',', on_bad_lines='skip')

v_data = pd.read_csv('/content/twitter_validation.csv')

data



v_data

data.columns = ['id', 'game', 'sentiment', 'text']
v_data.columns = ['id', 'game', 'sentiment', 'text']

data

v_data

data.shape

data.columns

data.describe(include='all')

id_types=data['id'].value_counts()
id_types

plt.figure(figsize=(12,7))
sns.barplot(y=id_types.index, x=id_types.values)
plt.xlabel('Type')
plt.ylabel('Count')
plt.title('# of Id vs Count')
plt.show()

game_types = data['game'].value_counts()
game_types

plt.figure(figsize=(14,10))

sns.barplot(x=game_types.values,y=game_types.index)
plt.title('# of Games and their count')
plt.ylabel('Type')
plt.xlabel('Count')

plt.show()

data.nunique()

v_data.nunique()